// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: deleteFollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM feed_follows
WHERE feed_id = $1
`

func (q *Queries) DeleteFollow(ctx context.Context, feedID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, feedID)
	return err
}
